### ISSUE TITLE
SUPPOT.APPLE.COM/MAC/STARTUP

### ISSUE THREAD

**Issue by vicar5235** [UHDbits/M73-Tiny-OpenCore#10]
Which do you have: an M73 Tiny or an M93p?: M73

Do your specifications match the ones shown in the README.md? (not including the USB WiFi adapter): YES 

If your specifications do not match, what are your specifications?:

What version of OS X/macOS are you using?: VENTURA 13.0

What is your issue?: Hello, thank you very much for providing the latest efi, but I seem to have encountered a problem. My machine is the nuc M73, which is the same thing as Lenovo M73. After installing ventura and using your efi, SUPPOT.APPLE.COM/mAC/STARTUP appears. How can I solve this problem?

Steps to reproduce your issue:

**Comment by UHDbits** [comment]
Strange question, but have you tried restarting and maybe just unplugging and replugging in your USB drive? This issue just seems to randomly happen to me, but, after a reboot, it's fixed.
Also, what macOS version are you trying to run? If you are running Ventura, make sure to download the latest commit, as the official release version doesn't support Ventura yet.
