### ISSUE TITLE
Chime sound

### ISSUE THREAD

**Issue by cenz92** [UHDbits/M73-Tiny-OpenCore#11]
Hello, I have a Lenovo m93p tiny with Monterey, everything is working for me, but I don't know how to work chime sound. Do you know how can I add it? Thanks

**Comment by cenz92** [comment]
Yes, if you can tell me which changes i can do, it's a great help, because i'm not using your opencore EFI cause I have an M93P with an i5 CPU, so it's different from yours. I tried to use the chime, but it's only working with the internal speaker, not with the DP output. Thanks for your help

**Comment by UHDbits** [comment]
Huh, I will try to help you out the best I can, but I don't use DP output, so I can't test that functionality for you. Do note, you can try to use my OC config, as it should support the M93p, but there's no guarantees that it'll work 100%. I've been busy with some stuff lately, but I'll try to help you out with this issue soon.

**Comment by cenz92** [comment]
I think I can't use your entire OC config, because my m93p has a different CPU (I5 4570) but same GPU (HD 4600), do you think it can work anyway? Thank you and don't worry, you're helping me, then i'm in no hurry ahahah.

**Comment by cenz92** [comment]
Hello, i have another problem, i tried to update to ventura following your instruction, but after oclp, i can't see anything on display after apple logo. Can you help me? Thanks

**Comment by UHDbits** [comment]
Did you change the SIP settings and add any boot-args? Those are required to run Ventura on this hardware. To do that, change "NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> csr-active-config" to "030A0000", and add "amfi_get_out_of_my_way=1 ipc_control_port_options=0" to NVRAM -> Add -> 7C436110-AB2A-4BBB-A880-FE41995C9F82 -> boot-args.

**Comment by cenz92** [comment]
Yes, i have those settings in nvram,but when i apply the oclp and reboot i don't see anything on screen,It says "no signal" after the Apple logo. Obviously i use the display port output

**Comment by UHDbits** [comment]
Mhm, that is interesting, because those settings were the only things that I had to change to make OCLP work on this ThinkCentre. Could you try adding "-v" to boot args, and take a picture of the last couple of lines before macOS gets stuck?
