### ISSUE TITLE
I5 4570T开机慢，并且键盘连击

### ISSUE THREAD

**Issue by cbmsy521** [UHDbits/M73-Tiny-OpenCore#13]
Which do you have: an M73 Tiny or an M93p?:

Do your specifications match the ones shown in the README.md? (not including the USB WiFi adapter):

If your specifications do not match, what are your specifications?:

What version of OS X/macOS are you using?:

What is your issue?:

Steps to reproduce your issue:

**Comment by cbmsy521** [comment]
求教一下，应该要改哪里呢？

**Comment by UHDbits** [comment]
抱歉，我不会说您的语言，但我会尽力提供帮助。您可以进入 BIOS 并尝试禁用 CSM 吗？
确保尝试切换此处显示的所有 BIOS 选项：https://github.com/UHDbits/M73-Tiny-OpenCore/blob/main/Resources/Documentation/BIOSSettings.md

另外，请您进一步解释一下您的键盘在启动时有什么问题吗？
