### ISSUE TITLE
macOS 14 Sonoma Support

### ISSUE THREAD

**Issue by UHDbits** [UHDbits/M73-Tiny-OpenCore#18]
With the very recent announcement of macOS 14 Sonoma, it's time to start working on getting it to run on this ThinkCentre! Please note that this can be a long process, or could possibly never happen. In order to get an experimental version of the configuration for macOS 14 Sonoma, check the ["sonoma"](https://github.com/UHDbits/M73-Tiny-OpenCore/tree/sonoma) branch.

All updates towards getting Sonoma working will be uploaded as comments below.

**Comment by UHDbits** [comment]
So, I'm not home right now, which means I don't have my ThinkCentre with me.

Luckily, I do have a Skylake laptop Hackintosh with me, so until I get home tomorrow, all updates below will be about getting Sonoma working on that.

I am currently downloading the InstallAssistant, then I will be attempting to install Sonoma. All updates will be posted below!

**Comment by UHDbits** [comment]
Good news! I've gotten further with a clean install, and I am now in the second stage of the installer!

Also, it seems like somebody in the OCLP Discord got Sonoma running on a Haswell Mac (not Hackintosh), with graphics acceleration working! This is very impressive and looking good for our ThinkCentre, as it took much longer to get graphics acceleration working on Ventura!

**Comment by UHDbits** [comment]
Great news, I was able to get Sonoma booted on the Skylake laptop, as mentioned above, even with graphics acceleration! Also good news, Sonoma has been booted on some Haswell Macs in the OCLP Discord, which means that it's likely that Sonoma will boot without issue on this ThinkCentre once some SMBIOS changes are made! This still means we don't have no graphics acceleration for the time being, but as progress on that is made, it will be posted here.

I hope to try to get Sonoma working as soon as I get home on Tuesday or Wednesday on the ThinkCentre.

**Comment by UHDbits** [comment]
I've now gotten home, so I'm going to start attempting to get Sonoma working with a very basic configuration!
Please do note, every year or so around WWDC, I like to completely rewrite my configurations using the knowledge I have gained over the past year, so it will likely take a while for a Sonoma config to be uploaded to the branch.

**Comment by UHDbits** [comment]
Good news, I have already gotten Sonoma booting on this ThinkCentre! Although, currently a lot of things are not functional, including graphics acceleration, WiFi, Bluetooth, and more. The configuration that I booted with was created very quickly, mainly just by disabling some kexts in the "main" branch and changing the SMBIOS. I want to at least start completely remaking the configuration before I upload it to the "sonoma" branch, which could take a while, but hopefully shouldn't take that long.

**Comment by UHDbits** [comment]
Sorry that I have been inactive recently, I've had some other tech stuff that I've been messing around with, plus starting a couple of new personal projects for myself. There is still a lot of work to go on the Sonoma branch, and I will probably skip a main 0.9.3 release for the repository. Thanks for understanding!

**Comment by UHDbits** [comment]
Glad to announce that I am now officially back and will be working on this project for the next week or so, hopefully finalizing the Sonoma configuration, starting work on the legacy configuration, and updating the main configuration to the latest OC version.

**Comment by UHDbits** [comment]
I am very happy to announce the Sonoma configuration is nearing 100% completion! I hope to upload the completed configuration tonight. I do want to note that of course, changes likely will not be merged into main until OCLP adds support for Sonoma. I may merge it early though, just because this configuration update is such a massive overhaul that I would like to get it out sooner rather then later. I'll likely merge the changes into main and just note that using Sonoma is **very** unrecommended.

**Comment by UHDbits** [comment]
I am very happy to announce that the hopefully final Sonoma configuration has been pushed to the "sonoma" branch! It will still need to be updated to OpenCore 0.9.4 once that releases, and there is still some documentation work that needs to be, plus some testing with Big Sur and Monterey, but after that, it should be done! I'm still considering pushing it before Sonoma support is added to OCLP because of just how major the configuration is, maybe I'll just strip Sonoma references or something.

With that, I leave you with this message that was pushed alongside the configuration. As mentioned, when the configuration has been pushed to "main", I'll create a more formal version.
"I have plans for this major update to be the last major update to this configuration, as after this, this configuration will have nearly been perfected. I will still provide updates to the latest kexts and OpenCore versions, and also provide support and documentation updates, but other than that, I think it's time to change my focus to other configurations and projects. Once this configuration is actually pushed to "main", I will make a more formal message. Thanks for the support over the past year of me making this OpenCore configuration."

This issue will be closed once the branches are merged.

**Comment by UHDbits** [comment]
I just remembered how last year I was able to get Ventura running a VM with graphics acceleration, not sure if that works this year with Sonoma, but I'm going to go and test it!

**Comment by UHDbits** [comment]
The VM trick does not work, but the great OCLP developers have recently released beta patches for graphics acceleration on GPUs like the one featured in our ThinkCentre, and I have confirmed that they work! There are some changes that I need to make to the "sonoma" branch for compatibility though, so I will try to get them done as soon as possible.

**Comment by UHDbits** [comment]
I hope to update this issue and upload final instructions for the OCLP guide when OCLP 1.0.0 releases in October. Alongside this, I will also update the OpenCore configuration to the latest version.

**Comment by UHDbits** [comment]
An update will be coming soon with proper Sonoma support.

**Comment by Hardness5466** [comment]
14.2 Enthusiasm and a fix for it!

If you did not install Open Core 1.3.0 BEFORE you installed macOS Sonoma 14.2 and you are wondering how to fix it without doing a clean install - try this: 

Put the Mac you want 14.2 on into target mode.
Connect to another Mac with OpenCore 1.3.0 installed
Run the build & install OpenCore task and install to the **target drive**
That fixed it for me. 

Message to self: Next time slow down and RTFM

I am successfully running 14.2 Sonoma on a MacBook Pro retina Mid 2012 15" 

Thanks Dortania!

**Comment by UHDbits** [comment]
In the latest version of this configuration (V0.9.7), proper Sonoma support has been added with WiFi support. Due to this, Sonoma is now considered a fully functional operating system, and this issue will now be closed.
