### ISSUE TITLE
sequoia

### ISSUE THREAD

**Issue by robi62** [UHDbits/M73-Tiny-OpenCore#19]
### What ThinkCentre model do you have?

m73t tiny

### What are your specifications?

i5 8 gb ram azurwave wifi

### What is your configuration version?

- [X] I am using the latest version of the configuration at the time of this question, or I will note the version I am using in my bug report below.
- [ ] I am using the legacy version of the configuration, and I am using Catalina or below.

### What version of macOS/OS X are you using?

Mac sequoia beta

### What is your question?

hi do you think it can work on sequoia beta``

**Comment by UHDbits** [comment]
OCLP does not yet have support for Sequoia on Metal 1 (3802) cards, so if Sequoia did run on this machine, it would be an incredibly poor experience. I am going to wait for proper support to be added to those cards (if it ever happens), before making a version of this config for Sequoia.

**Comment by robi62** [comment]
perfect thanks
