### ISSUE TITLE
I can't get 4K 60Hz Display

### ISSUE THREAD

**Issue by NatureProtect** [UHDbits/M73-Tiny-OpenCore#3]
Which do you have: an M73 Tiny or an M93p?:

Do your specs match the ones shown in the README.md (minus the USB WiFi adapter)?:

If your specs do not match, what are your specs?:

What version of OS X/macOS are you using?:

What is your issue?:

Steps to reproduce your issue:

**Comment by NatureProtect** [comment]
Hello, I have a lenovo m73, I used to DP to connect my display. It's KOIOS company 4K 60Hz,But On montery， I only output 4K  30Hz，Please help me

**Comment by UHDbits** [comment]
Hello! Were you able to get 4K60 on any other OS? I didn't think this ThinkCentre was capable of 4K60.

**Comment by UHDbits** [comment]
Nevermind, it seems to be a common issue with macOS. There is various solutions though, so I'll try to send you some so we can fix this.

**Comment by UHDbits** [comment]
![Screenshot_20220701-055228~2.png](https://user-images.githubusercontent.com/66931349/176898324-f6a927ae-7cb3-408d-8515-fcfe14773762.png)
Do you mind attempting to add this bootarg to your OpenCore config? If it doesn't work, please let me know.

**Comment by NatureProtect** [comment]
Thanks for support. It's nice 4K 60Hz worked on Windows10.
"-cdfon" I had add to config. but only 4K 30Hz.
My config:
                        <key>7C436110-AB2A-4BBB-A880-FE41995C9F82</key>
			<dict>
				<key>#INFO (prev-lang:kbd)</key>
				<string>en:252 (ABC), set 656e3a323532</string>
				<key>ForceDisplayRotationInEFI</key>
				<integer>0</integer>
				<key>SystemAudioVolume</key>
				<data>Rg==</data>
				<key>boot-args</key>
				<string>-cdfon</string>
				<key>csr-active-config</key>
				<data>AAAAAA==</data>
				<key>prev-lang:kbd</key>
				<string>en-US:0</string>
				<key>run-efi-updater</key>
				<string>No</string>
			</dict>

**Comment by UHDbits** [comment]
Mhm, ok. I have a couple more solutions to try but let me find one that might be the most likely to work.

**Comment by UHDbits** [comment]
Yeah okay. Again, this seems to be a very common and solvable issue, but there's a lot of different ways to solve it. I'm going to send you another way to attempt to solve it in just a small bit.

**Comment by UHDbits** [comment]
I need to install Monterey to help solve the issue, currently running Ventura but I can't send you a screen recording from it. Meanwhile, you can try some other methods that I'm going to send you. Quick question, do you have an HD4400 or an HD4600 as your iGPU? You can check in "About This Mac".

**Comment by NatureProtect** [comment]
My CPU is i5  4690t  ，so is  HD4600

**Comment by UHDbits** [comment]
Ok, so I made a new config that has all the settings that people say should make 4K60 work on Big Sur and Monterey. This config is bloated with options though, so I do not recommend using it as a daily and is mainly meant for testing to see if we can get this working.

**PLEASE put this config on a USB**, not on your hard drive. It's untested so I'm not sure if it will even boot, so I want to make sure you have another way to boot in case this config does not work.

If you get a black screen, some people said turning their monitor off and on just worked? Try that if it happens
[EFI.zip](https://github.com/UHDbits/M73-Tiny-OpenCore/files/9030447/EFI.zip)

**Comment by NatureProtect** [comment]
oh，sorry
your efi is not work，my display still is 4K 60Hz

**Comment by NatureProtect** [comment]
![Uploading IMG_20220702_010752.jpg…]()

**Comment by NatureProtect** [comment]
maybe its ok，i try it again

**Comment by UHDbits** [comment]
Mhm, okay. Does the config at least boot? Could you try to use this application to force 4k60? https://github.com/avibrazil/RDM

**Comment by NatureProtect** [comment]
O My God，the efi is ok。
Now the display is 4K 60Hz，after I refresh the   display resolution set。
Thanks a lot，very nice

**Comment by UHDbits** [comment]
Nice! You didn't have to use the RDM application?
I'm going to send you a less bloated EFI and if you could test it that would be great!

**Comment by NatureProtect** [comment]
I didn't use RDM

**Comment by UHDbits** [comment]
If you do not mind, please try this config:
[EFI.zip](https://github.com/UHDbits/M73-Tiny-OpenCore/files/9030686/EFI.zip)

If that config does not work, please try this one:
[EFI 2.zip](https://github.com/UHDbits/M73-Tiny-OpenCore/files/9030688/EFI.2.zip)

If neither of them work, please let me know.

**Comment by NatureProtect** [comment]
hello，on my PC
the first  efi will make display solution become 2K 60Hz
thesecond efi-2 is worked nice  4k 60Hz

**Comment by UHDbits** [comment]
Ok, thanks! I'll test the config on my ThinkCentre to make sure it doesn't break anything for 1080p and then I'll push the changed into the main branch. Thanks for reporting the issue!

**Comment by UHDbits** [comment]
This issue has been fixed with commit 8caef5cf1aac61c434c8698becb4e531d95181ca in "main" and with commit 24fc53cc41f5f97f02c662082138c3e42e93518e in "ventura". Thank you @NatureProtect! This issue will now be closed. Please reopen if you have any further issues with this exact issue, or make a new issue.
