### ISSUE TITLE
DP display sleep wake and black screen

### ISSUE THREAD

**Issue by NatureProtect** [UHDbits/M73-Tiny-OpenCore#5]
Which do you have: an M73 Tiny or an M93p?:  M73

Do your specs match the ones shown in the README.md (minus the USB WiFi adapter)?:  

If your specs do not match, what are your specs?:
CPU： i5-4690t
wifi：no wifi
What version of OS X/macOS are you using?:
Monterey

What is your issue?:
Sorry, it's me again.
I found my Mac will black screen after sleep wake up. and the display's light is on.
Please help
Steps to reproduce your issue:

**Comment by UHDbits** [comment]
Just to make sure it's not an issue with our previous 4K60 fix, could you please set your monitor to 1080p60 and test sleep and wake?

**Comment by NatureProtect** [comment]
I set the monitor to 1080p60 and sleep and wake， same situation， black screen.
4K60 and 1080p60，it could normal screen after wake up multiple times.
I don't know your situation.  Please try to wake up after 20 minutes of monitor sleep. It maybe black screen.
In addition to that， my pc audio not output after wake up.

**Comment by UHDbits** [comment]
Ok, I'm going to be away from my ThinkCentre for a week or so but I'll try sending solutions in the meantime.

**Comment by UHDbits** [comment]
So, I'm not at my computer right now, but could you try switching your power state to iirc "C1C3C6"? It should be in the BIOS settings, CPU setup and it should be somewhere there. See if sleep and wake works.

**Comment by UHDbits** [comment]
So, I'm not at my computer right now, but could you try switching your power state to iirc "C1C3C6"? It should be in the BIOS settings, CPU setup and it should be somewhere there. See if sleep and wake works.

**Comment by NatureProtect** [comment]
Sorry for the late reply,   switched the power state to iirc "C1C3C6" is not worked.
Today, I found it works when I switch the display to hdmi and then wake up the mac (DP display).
A lot of white apples say something similar, It maybe not hackintosh‘s question.
It's solved, thanks again

**Comment by UHDbits** [comment]
Ok, thank you. I'll try to replicate the problem and if I can't then I will go ahead and close this issue.

**Comment by UHDbits** [comment]
I was not able to replicate this issue. If anyone else has this issue, please follow the advice above of switching inputs.
